name = "miaoda-react-admin-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
WIX_API_KEY = "IST.eyJraWQiOiJQb3pIX2FDMiIsImFsZyI6IlJTMjU2In0.eyJkYXRhIjoie1wiaWRcIjpcImYyYmE2NmMwLTdkNjItNDQwYi05NWY1LTBjYTZmOWI3OWI5NVwiLFwiaWRlbnRpdHlcIjp7XCJ0eXBlXCI6XCJhcHBsaWNhdGlvblwiLFwiaWRcIjpcImJiNjM2MGQ3LWVjOWUtNGYxZi05ZTNmLTg4MTFjYjBjZWE1N1wifSxcInRlbmFudFwiOntcInR5cGVcIjpcImFjY291bnRcIixcImlkXCI6XCI2NDFiNzMzOC1kMzgyLTRhYmEtYTc1ZS1hZGUxZjM1NDQxZTlcIn19IiwiaWF0IjoxNzg1NzAyOTY0fQ.dpGQ703rzbLy8mU6rec2zyUOBxzgs8gF4hYV2Lgxd6CPCkFwpCYTR8b0xs_zooFRApOqpjzG9OFaEZ4z6ZbFGDlkLq5YujyCFBIW1-mmoNgG6bMmvKMwjuJnDiNgdyXeAcMG12tRaNmHMWVTjM3wgmhj7qlSvAyGiPdhW3L7xV54k4IL1xChZgy8wl0C82FQFT-y1DKyWCVBtO3ranmd6uG5tF-y-iAMi8nnj0adtnRo__1932a75JwyqjBHzzVl-WNca_Ww5QUajQBY9hgNYhwi9DsHIgBWT_dfuECiXQ_NKNBE79gwC5JRt90qPw9I-lDtsBZcEjAzkDqyf2pUKA"
WIX_SITE_ID = "4eefbfa5-79cc-4e20-ac97-76dc881fd57b"
WIX_ACCOUNT_ID = "641b7338-d382-4aba-a75e-ade1f35441e9"
